# .pre-commit-config.yaml
repos:
  # 基本的なファイルチェック
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: pretty-format-json
        args: ["--autofix", "--indent=2"]

  # Prettier（フォーマッター）
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [css, scss, javascript, ts, tsx, json, yaml, markdown]
        exclude: |
          (?x)^(
              \.github/.*\.yml|
              \.github/.*\.yaml|
              package-lock\.json|
              .*\.min\.(js|css)
          )$

  # Python関連
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      # Ruff linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Ruff formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: \.py$
        additional_dependencies: [types-all]

  # JavaScript/TypeScript関連
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        additional_dependencies:
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "eslint-config-prettier"
          - "eslint-plugin-import"

  # CSS/SCSS関連
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v15.11.0
    hooks:
      - id: stylelint
        files: \.(css|scss|sass)$
        additional_dependencies:
          - "stylelint"
          - "stylelint-config-standard"
          - "stylelint-config-prettier"
          - "stylelint-scss"

  # Markdown関連
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
        exclude: 'CHANGELOG\.md'

  # コミットメッセージのチェック
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # シークレット検出
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", "./.secrets.baseline"]
        exclude: package-lock.json

# グローバル設定
default_language_version:
  python: python3.11
  node: "18.19.0"

# CI設定
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
