# サイト全体の情報
site_name: 'DevBlueprint'
docs_dir: 'Docs'
site_url: 'https://BitzLabs.github.io/DevBlueprint/'
site_author: 'BitzLabs'
site_description: 'ソフトウェア開発のための設計図 (Living Blueprint)'

# リポジトリへのリンク (サイト右上のアイコン)
repo_url: 'https://github.com/BitzLabs/DevBlueprint'
repo_name: 'DevBlueprint'

# 各ページの「編集」ボタンのリンク先を設定
edit_uri: 'edit/main/Docs/'

# テーマと機能
theme:
  name: material
  language: ja
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Markdown拡張機能 (表現力を高める)
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

# JavaScript追加
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Markdown拡張機能 (プラグイン設定)
plugins:
  - search # (検索機能はデフォルトで有効ですが、明記しておくと確実です)
  - exclude:
      glob:
        # Visual Studio & .NET が生成するフォルダ
        - "**/bin/**"
        - "**/obj/**"
        - "**/.vs/**"
        # Visual Studio のソリューション/プロジェクトファイル
        - "**/*.sln"
        - "**/*.csproj"
        - "**/*.user"
        # Node.js の依存関係フォルダ (CLIツール導入時に備えて)
        - "**/node_modules/**"
        # その他、Git管理ファイルなど
        - ".gitignore"
        - ".git/**"

# ナビゲーション (サイトのサイドバーメニュー)
nav:
  - ホーム: README.md
  - プロジェクト管理:
    - 概要: 00_プロジェクト管理/README.md
    - ロードマップ: 00_プロジェクト管理/01_ロードマップ.md
  - 要求仕様:
    - 全体仕様: 01_要求仕様/README.md
    - 機能要件:
      - 概要: 01_要求仕様/01_機能要件/README.md
      - ナビゲーション自動生成: 01_要求仕様/01_機能要件/01_ナビゲーション自動生成機能.md
      - ラベル自動化: 01_要求仕様/01_機能要件/02_ラベル自動化機能.md
      - プロジェクト初期化: 01_要求仕様/01_機能要件/03_プロジェクト初期化機能.md
      - ロードマップ機能: 01_要求仕様/01_機能要件/04_ロードマップ機能.md
    - ユースケース:
      - 概要: 01_要求仕様/02_ユースケース/README.md
  - 設計仕様:
    - 概要: 02_設計仕様/README.md
    - API仕様:
      - 概要: 02_設計仕様/01_API仕様書/README.md
    - データ仕様:
      - 概要: 02_設計仕様/02_データ仕様書/README.md
    - UI/UX仕様:
      - 概要: 02_設計仕様/03_UIUX仕様書/README.md
  - 開発ルール:
    - 概要: 03_開発ルール/README.md
    - セットアップガイド: 03_開発ルール/00_セットアップガイド.md
    - フォルダ構成:
      - ルートディレクトリ: 03_開発ルール/01_フォルダ構成/01_ルートディレクトリ.md
      - Docsフォルダ: 03_開発ルール/01_フォルダ構成/02_Docsフォルダ.md
      - Srcフォルダ: 03_開発ルール/01_フォルダ構成/03_Srcフォルダ.md
      - Testsフォルダ: 03_開発ルール/01_フォルダ構成/04_Testsフォルダ.md
      - Sandboxフォルダ: 03_開発ルール/01_フォルダ構成/05_Sandboxフォルダ.md
    - プロジェクト規定:
      - 開発フロー概要: 03_開発ルール/02_プロジェクト規定/01_開発フロー概要.md
      - ラベル規定: 03_開発ルール/02_プロジェクト規定/02_ラベル規定.md
      - マイルストーン規定: 03_開発ルール/02_プロジェクト規定/03_マイルストーン規定.md
      - Issue規定: 03_開発ルール/02_プロジェクト規定/04_Issue規定.md
      - ブランチ規定: 03_開発ルール/02_プロジェクト規定/05_ブランチ規定.md
      - プルリクエスト規定: 03_開発ルール/02_プロジェクト規定/06_プルリクエスト規定.md
    - ドキュメント規定:
      - ドキュメント規則: 03_開発ルール/03_ドキュメント規定/01_ドキュメント規則.md
    - コーディング規定:
      - 概要: 03_開発ルール/04_コーディング規定/README.md
      - C#規約: 03_開発ルール/04_コーディング規定/CSharp/01_コーディング規約_CSharp.md
    - リリース規定:
      - 概要: 03_開発ルール/05_リリース規定/README.md
  - テスト仕様:
    - 概要: 04_テスト仕様/README.md
