# サイト全体の情報
site_name: 'DevBlueprint'
site_url: 'https://BitzLabs.github.io/DevBlueprint/'
site_author: 'BitzLabs'
site_description: '高品質なソフトウェア開発のための、生きた設計図 (Living Blueprint)'

# リポジトリへのリンク (サイト右上のアイコン)
repo_url: 'https://github.com/BitzLabs/DevBlueprint'
repo_name: 'DevBlueprint'

# 各ページの「編集」ボタンのリンク先を設定
edit_uri: 'edit/main/docs/'

# テーマと機能
theme:
  name: material
  language: ja
  logo: assets/images/logo.svg # (オプション) ロゴ画像を配置する場合のパス
  favicon: assets/images/favicon.png # (オプション) ファビコンを配置する場合のパス
  features:
    - navigation.tabs # 上部にタブナビゲーションを表示
    - navigation.top  # ページ上部に戻るボタン
    - navigation.sections # 左サイドバーをセクションごとに開閉可能に (推奨)
    - search.suggest      # 検索のサジェスト機能
    - search.highlight    # 検索結果のキーワードをハイライト
    - content.code.annotate # コードブロックに注釈を追加
  palette:
    # ライトモード
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # ダークモード
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Markdown拡張機能 (表現力を高める)
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

# ナビゲーション (サイトのサイドバーメニュー)
# ここでドキュメントの階層構造を定義します。
nav:
  - ホーム: README.md
  - プロジェクト管理:
    - 概要: 00_プロジェクト管理/README.md
    - ロードマップ: 00_プロジェクト管理/01_ロードマップ.md
  - 要求仕様:
    - 全体仕様: 01_要求仕様/README.md  # READMEを全体仕様として表示
    - 機能要件:
      - 概要: 01_要求仕様/01_機能要件/README.md
      - 認証機能 (例): 01_要求仕様/01_機能要件/REQ_01_認証機能.md
    - ユースケース:
      - 概要: 01_要求仕様/02_ユースケース/README.md
      - ユーザー登録 (例): 01_要求仕様/02_ユースケース/UC_01_ユーザー登録.md
  - 設計仕様:
    - 概要: 02_設計仕様/README.md
    - アーキテクチャ概要 (例): 02_設計仕様/00_アーキテクチャ概要.md # 未分類の設計書
    - API仕様:
      - 概要: 02_設計仕様/01_API仕様書/README.md
      - API設計規約: 02_設計仕様/01_API仕様書/01_API設計規約.md
    - データ仕様:
      - 概要: 02_設計仕様/02_データ仕様書/README.md
      - データモデル: 02_設計仕様/02_データ仕様書/01_データモデル設計書.md
    - UI/UX仕様:
      - 概要: 02_設計仕様/03_UIUX仕様書/README.md
      - 画面一覧: 02_設計仕様/03_UIUX仕様書/01_画面一覧.md
  - 開発ルール:
    - 概要: 03_開発ルール/README.md
    - ブランチ戦略: 03_開発ルール/01_ブランチ戦略.md
    - コーディング規約: 03_開発ルール/02_コーディング規約.md
  - テスト仕様:
    - 概要: 04_テスト仕様/README.md
    - テスト計画と報告: 04_テスト仕様/01_テスト計画と報告_Template.md
    - テストケース:
      - 概要: 04_テスト仕様/02_テストケース/README.md
