# サイト全体の情報
site_name: 'DevBlueprint'
docs_dir: 'Docs'
site_url: 'https://BitzLabs.github.io/DevBlueprint/'
site_author: 'BitzLabs'
site_description: 'ソフトウェア開発のための設計図 (Living Blueprint)'

# リポジトリへのリンク (サイト右上のアイコン)
repo_url: 'https://github.com/BitzLabs/DevBlueprint'
repo_name: 'DevBlueprint'

# 各ページの「編集」ボタンのリンク先を設定
edit_uri: 'edit/main/Docs/'

# テーマと機能
theme:
  name: material
  language: ja
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Markdown拡張機能 (表現力を高める)
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

# Markdown拡張機能 (プラグイン設定)
plugins:
  - search # (検索機能はデフォルトで有効ですが、明記しておくと確実です)
  - exclude:
      glob:
        # Visual Studio & .NET が生成するフォルダ
        - "**/bin/**"
        - "**/obj/**"
        - "**/.vs/**"
        # Visual Studio のソリューション/プロジェクトファイル
        - "**/*.sln"
        - "**/*.csproj"
        - "**/*.user"
        # Node.js の依存関係フォルダ (CLIツール導入時に備えて)
        - "**/node_modules/**"
        # その他、Git管理ファイルなど
        - ".gitignore"
        - ".git/**"

# ナビゲーション (サイトのサイドバーメニュー)
nav:
  - ホーム: README.md
  - プロジェクト管理:
    - 概要: 00_プロジェクト管理/README.md
    - ロードマップ: 00_プロジェクト管理/01_ロードマップ.md
  - 要求仕様:
    - 全体仕様: 01_要求仕様/README.md
    - 機能要件:
      - 概要: 01_要求仕様/01_機能要件/README.md
      - 認証機能 (例): 01_要求仕様/01_機能要件/REQ_01_認証機能.md
    - ユースケース:
      - 概要: 01_要求仕様/02_ユースケース/README.md
      - ユーザー登録 (例): 01_要求仕様/02_ユースケース/UC_01_ユーザー登録.md
      - テンプレート: 01_要求仕様/02_ユースケース/_Template.md
  - 設計仕様:
    - 概要: 02_設計仕様/README.md
    - アーキテクチャ概要 (例): 02_設計仕様/00_アーキテクチャ概要.md
    - API仕様:
      - 概要: 02_設計仕様/01_API仕様書/README.md
      - API設計規約: 02_設計仕様/01_API仕様書/01_API設計規約.md
    - データ仕様:
      - 概要: 02_設計仕様/02_データ仕様書/README.md
      - データモデル (テンプレート): 02_設計仕様/02_データ仕様書/01_データモデル設計書_Template.md
    - UI/UX仕様:
      - 概要: 02_設計仕様/03_UIUX仕様書/README.md
      - 画面一覧 (例): 02_設計仕様/03_UIUX仕様書/01_画面一覧.md
      - 画面仕様書 (テンプレート): 02_設計仕様/03_UIUX仕様書/02_画面仕様書_Template.md
  - 開発ルール:
    - 概要: 03_開発ルール/README.md
    - ブランチ戦略: 03_開発ルール/01_ブランチ戦略.md
    - コーディング規約: 03_開発ルール/02_コーディング規約.md
  - テスト仕様:
    - 概要: 04_テスト仕様/README.md
    - テスト計画と報告 (テンプレート): 04_テスト仕様/01_テスト計画と報告_Template.md
    - テストケース:
      - 概要: 04_テスト仕様/02_テストケース/README.md
      - テンプレート: 04_テスト仕様/02_テストケース/_Template.md
      - 認証機能のテスト (例): 04_テスト仕様/02_テストケース/AUTH/TC-AUTH-001.md

exclude:
  - '**/bin'
  - '**/obj'
  - '**/.vs'
  - '**/*.sln'
  - '**/*.csproj'
  - '**/*.user'
