services:
  mkdocs:
    build:
      context: ./mkdocs
      dockerfile: Dockerfile
    container_name: devblueprint-mkdocs
    ports:
      - "8000:8000"
    volumes:
      - ../:/docs
      - /docs/Docker/mkdocs/site # サイト生成ファイルをDocker/mkdocs/site内に保持
    environment:
      - PYTHONUNBUFFERED=1
    command: mkdocs serve --dev-addr=0.0.0.0:8000 --livereload
    restart: unless-stopped
    networks:
      - mkdocs-network

networks:
  mkdocs-network:
    driver: bridge
